### ISSUE TITLE
For some reason we get a long stack trace during runtime

### ISSUE THREAD

**Issue by phistr2** [agustavsson/projinda16#15]
It appears twice everytime a gas can is picked up. It says: 

``` Java
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
```

and a couple of lines after that:

``` Java
    at Motor.hasLost(Motor.java:106)
    at Motor.lambda$start$2(Motor.java:91)
```

**Comment by phistr2** [comment]
We had an incorrect way of removing entities that had been picked up, now it works fine, it however still adds 2 to score everytime it's picked up
